#!/bin/bash
. ../lib/processman

#session_dir=$AREX_RUN_DIR/sessions
session_dir=$AREX_RUN_DIR/sessions


# start a php-fpm server
function start_fpm()
{
  listen="$1"
  if [ -z "$listen" ]; then
    listen="127.0.0.1:$AREX_FCGI_PORT"
  fi

  # session dir
  mkdir $session_dir

  echo -n 'Starting php-fpm .. '
cat << EOF > $AREX_RUN_DIR/php-fpm.conf
[global]
pid       = $AREX_RUN_DIR/php-fpm.pid
error_log = $AREX_RUN_DIR/php-fpm.log

[www]
listen   = $listen
pm                   = dynamic
pm.max_children      = 5
pm.start_servers     = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3
php_value[session.save_handler] = files
php_value[session.save_path] = $session_dir
EOF
  php-fpm --fpm-config $AREX_RUN_DIR/php-fpm.conf
  sleep 1
  echo $(cat $AREX_RUN_DIR/php-fpm.pid)
  echo
}

# stop php-fpm server
function stop_fpm()
{
  echo -n 'Stopping php-fpm ... '
  kill_pid_port $(cat $AREX_RUN_DIR/php-fpm.pid) $AREX_FCGI_PORT && echo 'done.' || echo 'FAILED.'
  echo "session files in $session_dir"
}

